import 'package:bmicalculator/constants/height_bar.dart';
import 'package:flutter/material.dart';

class Rule extends StatelessWidget {
  const Rule({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: const [
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
          HeightBar(barWidth: 30),
          SizedBox(height: 10),
          HeightBar(barWidth: 20),
          SizedBox(height: 10),
        ]);
  }
}
